services:
  web:
    build: .
    command: >
      sh -c "pip install --no-cache-dir -r requirements.txt && 
      python manage.py migrate && 
      gunicorn --bind 0.0.0.0:8000 task_list.wsgi"
    volumes:
      - static_volume:/app/static
    expose:
      - 8000
    env_file:
      - ./.env.compose
    depends_on:
      - db

  db:
    image: postgres:17.0-alpine
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    env_file:
      - ./.env.compose

  nginx:
    build: ./nginx
    volumes:
      - static_volume:/app/static
    ports:
      - 80:80
    depends_on:
      - web

volumes:
  postgres_data:
  static_volume: